/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface EonFlip {
    'flip': () => void;
    'flipButtonId': string;
    'flipSelector': string;
    'flipType': 'hover' | 'click' | 'button';
    'type': 'static' | 'flip' | 'pass';
    'visible': number;
  }
  interface EonFlipAttributes extends StencilHTMLAttributes {
    'flipButtonId'?: string;
    'flipSelector'?: string;
    'flipType'?: 'hover' | 'click' | 'button';
    'type'?: 'static' | 'flip' | 'pass';
    'visible'?: number;
  }

  interface EonInput {
    'accept': string | undefined;
    'autocapitalize': string;
    'autocomplete': 'off' | 'on';
    'autocorrect': 'off' | 'on';
    'autofocus': boolean;
  }
  interface EonInputAttributes extends StencilHTMLAttributes {
    'accept'?: string | undefined;
    'autocapitalize'?: string;
    'autocomplete'?: 'off' | 'on';
    'autocorrect'?: 'off' | 'on';
    'autofocus'?: boolean;
  }

  interface EonEngageHome {}
  interface EonEngageHomeAttributes extends StencilHTMLAttributes {}

  interface EonEngageRoot {}
  interface EonEngageRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'EonFlip': Components.EonFlip;
    'EonInput': Components.EonInput;
    'EonEngageHome': Components.EonEngageHome;
    'EonEngageRoot': Components.EonEngageRoot;
  }

  interface StencilIntrinsicElements {
    'eon-flip': Components.EonFlipAttributes;
    'eon-input': Components.EonInputAttributes;
    'eon-engage-home': Components.EonEngageHomeAttributes;
    'eon-engage-root': Components.EonEngageRootAttributes;
  }


  interface HTMLEonFlipElement extends Components.EonFlip, HTMLStencilElement {}
  var HTMLEonFlipElement: {
    prototype: HTMLEonFlipElement;
    new (): HTMLEonFlipElement;
  };

  interface HTMLEonInputElement extends Components.EonInput, HTMLStencilElement {}
  var HTMLEonInputElement: {
    prototype: HTMLEonInputElement;
    new (): HTMLEonInputElement;
  };

  interface HTMLEonEngageHomeElement extends Components.EonEngageHome, HTMLStencilElement {}
  var HTMLEonEngageHomeElement: {
    prototype: HTMLEonEngageHomeElement;
    new (): HTMLEonEngageHomeElement;
  };

  interface HTMLEonEngageRootElement extends Components.EonEngageRoot, HTMLStencilElement {}
  var HTMLEonEngageRootElement: {
    prototype: HTMLEonEngageRootElement;
    new (): HTMLEonEngageRootElement;
  };

  interface HTMLElementTagNameMap {
    'eon-flip': HTMLEonFlipElement
    'eon-input': HTMLEonInputElement
    'eon-engage-home': HTMLEonEngageHomeElement
    'eon-engage-root': HTMLEonEngageRootElement
  }

  interface ElementTagNameMap {
    'eon-flip': HTMLEonFlipElement;
    'eon-input': HTMLEonInputElement;
    'eon-engage-home': HTMLEonEngageHomeElement;
    'eon-engage-root': HTMLEonEngageRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
