/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  ImageStyle,
  Size,
  UploadStyle,
  UploadType,
} from './types/theme';


export namespace Components {

  interface EonButton {
    'buttonType': string;
    'color': string | undefined;
    'disabled': boolean;
    'enableToggle': boolean;
    'endLoading': () => void;
    'expand': 'block' | 'full' | undefined;
    'fill': 'clear' | 'default' | 'outline' | 'solid' | undefined;
    'href': string | undefined;
    'icon': string;
    'iconSize': string;
    'loading': boolean;
    'loadingColor': any;
    'loadingCurrent': any;
    'loadingMax': any;
    'loadingMin': any;
    'loadingType': 'bar' | 'spinner' | 'full' | 'center';
    'mode': 'ios' | 'md';
    'onClick': (event) => any;
    'preventDefault': boolean;
    'rightIcon': string;
    'routerDirection': 'back' | 'forward' | 'root';
    'setLoadingCurrent': (loadingCurrent: any) => void;
    'shape': 'round' | undefined;
    'size': Size | 'default' | 'large' | 'small' | undefined;
    'startLoading': () => void;
    'stop': boolean;
    'stopPropagation': boolean;
    'strong': boolean;
    'target': string;
    'toggle': () => void;
    'toggleLoading': () => void;
    'tooltip': string;
    'tooltipPosition': 'top' | 'bottom' | 'left' | 'right';
    'type': 'button' | 'reset' | 'submit';
  }
  interface EonButtonAttributes extends StencilHTMLAttributes {
    'buttonType'?: string;
    'color'?: string | undefined;
    'disabled'?: boolean;
    'enableToggle'?: boolean;
    'expand'?: 'block' | 'full' | undefined;
    'fill'?: 'clear' | 'default' | 'outline' | 'solid' | undefined;
    'href'?: string | undefined;
    'icon'?: string;
    'iconSize'?: string;
    'loading'?: boolean;
    'loadingColor'?: any;
    'loadingCurrent'?: any;
    'loadingMax'?: any;
    'loadingMin'?: any;
    'loadingType'?: 'bar' | 'spinner' | 'full' | 'center';
    'mode'?: 'ios' | 'md';
    'onClick'?: (event) => any;
    'onEonAction'?: (event: CustomEvent) => void;
    'preventDefault'?: boolean;
    'rightIcon'?: string;
    'routerDirection'?: 'back' | 'forward' | 'root';
    'shape'?: 'round' | undefined;
    'size'?: Size | 'default' | 'large' | 'small' | undefined;
    'stop'?: boolean;
    'stopPropagation'?: boolean;
    'strong'?: boolean;
    'target'?: string;
    'tooltip'?: string;
    'tooltipPosition'?: 'top' | 'bottom' | 'left' | 'right';
    'type'?: 'button' | 'reset' | 'submit';
  }

  interface EonFlip {
    'flip': () => void;
    'flipButtonId': string;
    'flipSelector': string;
    'flipType': 'hover' | 'click' | 'button';
    'type': 'static' | 'flip' | 'pass';
    'visible': number;
  }
  interface EonFlipAttributes extends StencilHTMLAttributes {
    'flipButtonId'?: string;
    'flipSelector'?: string;
    'flipType'?: 'hover' | 'click' | 'button';
    'type'?: 'static' | 'flip' | 'pass';
    'visible'?: number;
  }

  interface EonForm {
    'adapter': any;
    'allowUndefined': boolean;
    'bindSelector': string;
    'eonId': string | number;
    'errorSelector': string;
    'getValues': () => object;
    'handleUpload': boolean;
    'inputSelector': string;
    'path': string;
    'propertyNameAttribute': string;
    'refresh': boolean;
    'reset': () => void;
    'setValue': (value?: object) => void;
    'submit': () => void;
    'type': 'save' | 'update' | 'patch' | 'create' | 'custom';
    'uploadSelector': string;
    'value': object;
  }
  interface EonFormAttributes extends StencilHTMLAttributes {
    'adapter'?: any;
    'allowUndefined'?: boolean;
    'bindSelector'?: string;
    'eonId'?: string | number;
    'errorSelector'?: string;
    'handleUpload'?: boolean;
    'inputSelector'?: string;
    'onOnSubmit'?: (event: CustomEvent) => void;
    'path'?: string;
    'propertyNameAttribute'?: string;
    'refresh'?: boolean;
    'type'?: 'save' | 'update' | 'patch' | 'create' | 'custom';
    'uploadSelector'?: string;
    'value'?: object;
  }

  interface EonInput {
    'accept': string | undefined;
    'autocapitalize': string;
    'autocomplete': 'off' | 'on';
    'autocorrect': 'off' | 'on';
    'autofocus': boolean;
    'bind': any;
    'bindSelector': string;
    'clear': () => void;
    'clearInput': boolean;
    'clearOnEdit': boolean | undefined;
    'color': string | undefined;
    'cols': number | undefined;
    'debounce': number;
    'disabled': boolean;
    'errorMsg': string;
    'errorSelector': string;
    'getName': () => string;
    'getValue': () => any;
    'inputmode': string | undefined;
    'itemButton': boolean;
    'itemColor': string | undefined;
    'itemDetail': boolean | undefined;
    'itemDetailIcon': string;
    'itemDisabled': boolean;
    'itemHref': string | undefined;
    'itemLines': "full" | "inset" | "none" | undefined;
    'itemMode': "ios" | "md";
    'itemRouterDirection': "back" | "forward" | "root";
    'itemType': "button" | "reset" | "submit";
    'label': string;
    'labelColor': string | undefined;
    'labelMode': 'ios' | 'md';
    'labelPosition': 'floating' | 'fixed' | 'stacked' | undefined;
    'max': string | undefined;
    'maxlength': number | undefined;
    'min': string | undefined;
    'minlength': number | undefined;
    'mode': 'ios' | 'md';
    'multiple': boolean | undefined;
    'name': string;
    'pattern': string | undefined;
    'placeholder': null | string | undefined;
    'readonly': boolean;
    'required': boolean;
    'rows': number | undefined;
    'setFocus': () => void;
    'setValue': (value?: string) => void;
    'size': number | undefined;
    'spellcheck': boolean;
    'step': string | undefined;
    'successMsg': string;
    'textarea': boolean;
    'type': 'date' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'time' | 'url';
    'value': null | string | undefined | number;
    'wrap': 'hard' | 'off' | 'soft' | undefined;
  }
  interface EonInputAttributes extends StencilHTMLAttributes {
    'accept'?: string | undefined;
    'autocapitalize'?: string;
    'autocomplete'?: 'off' | 'on';
    'autocorrect'?: 'off' | 'on';
    'autofocus'?: boolean;
    'bind'?: any;
    'bindSelector'?: string;
    'clearInput'?: boolean;
    'clearOnEdit'?: boolean | undefined;
    'color'?: string | undefined;
    'cols'?: number | undefined;
    'debounce'?: number;
    'disabled'?: boolean;
    'errorMsg'?: string;
    'errorSelector'?: string;
    'inputmode'?: string | undefined;
    'itemButton'?: boolean;
    'itemColor'?: string | undefined;
    'itemDetail'?: boolean | undefined;
    'itemDetailIcon'?: string;
    'itemDisabled'?: boolean;
    'itemHref'?: string | undefined;
    'itemLines'?: "full" | "inset" | "none" | undefined;
    'itemMode'?: "ios" | "md";
    'itemRouterDirection'?: "back" | "forward" | "root";
    'itemType'?: "button" | "reset" | "submit";
    'label'?: string;
    'labelColor'?: string | undefined;
    'labelMode'?: 'ios' | 'md';
    'labelPosition'?: 'floating' | 'fixed' | 'stacked' | undefined;
    'max'?: string | undefined;
    'maxlength'?: number | undefined;
    'min'?: string | undefined;
    'minlength'?: number | undefined;
    'mode'?: 'ios' | 'md';
    'multiple'?: boolean | undefined;
    'name'?: string;
    'onEonBlur'?: (event: CustomEvent) => void;
    'onEonChange'?: (event: CustomEvent) => void;
    'onEonFocus'?: (event: CustomEvent) => void;
    'onEonInput'?: (event: CustomEvent) => void;
    'onEonInputDidLoad'?: (event: CustomEvent) => void;
    'onEonInputDidUnload'?: (event: CustomEvent) => void;
    'pattern'?: string | undefined;
    'placeholder'?: null | string | undefined;
    'readonly'?: boolean;
    'required'?: boolean;
    'rows'?: number | undefined;
    'size'?: number | undefined;
    'spellcheck'?: boolean;
    'step'?: string | undefined;
    'successMsg'?: string;
    'textarea'?: boolean;
    'type'?: 'date' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'time' | 'url';
    'value'?: null | string | undefined | number;
    'wrap'?: 'hard' | 'off' | 'soft' | undefined;
  }

  interface EonUpload {
    'accept': string;
    'adapter': any;
    'bindSelector': string;
    'clear': (event?: any) => void;
    'context': string;
    'engStyle': UploadStyle;
    'eonId': string;
    'errorMsg': string;
    'errorSelector': string;
    'getInputElement': () => HTMLInputElement;
    'imageStyle': ImageStyle;
    'mainImage': boolean;
    'method': string;
    'multiple': boolean;
    'name': string;
    'pause': () => void;
    'placeholder': string;
    'preview': boolean;
    'select': () => void;
    'setAdapter': (adapter: any, onlyIfMissing?: boolean) => any;
    'size': Size;
    'start': (event?: any, files?: any) => Promise<any[]>;
    'successMsg': string;
    'type': UploadType;
    'uploadOnSelect': boolean;
    'value': any;
  }
  interface EonUploadAttributes extends StencilHTMLAttributes {
    'accept'?: string;
    'adapter'?: any;
    'bindSelector'?: string;
    'context'?: string;
    'engStyle'?: UploadStyle;
    'eonId'?: string;
    'errorMsg'?: string;
    'errorSelector'?: string;
    'imageStyle'?: ImageStyle;
    'mainImage'?: boolean;
    'method'?: string;
    'multiple'?: boolean;
    'name'?: string;
    'onEonFileClear'?: (event: CustomEvent) => void;
    'onEonFileSelect'?: (event: CustomEvent) => void;
    'onEonUploadEnd'?: (event: CustomEvent) => void;
    'onEonUploadProgress'?: (event: CustomEvent) => void;
    'onEonUploadStart'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'preview'?: boolean;
    'size'?: Size;
    'successMsg'?: string;
    'type'?: UploadType;
    'uploadOnSelect'?: boolean;
    'value'?: any;
  }

  interface EonEngageBootstrap {}
  interface EonEngageBootstrapAttributes extends StencilHTMLAttributes {}

  interface EonEngageHome {}
  interface EonEngageHomeAttributes extends StencilHTMLAttributes {}

  interface EonEngageRoot {}
  interface EonEngageRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'EonButton': Components.EonButton;
    'EonFlip': Components.EonFlip;
    'EonForm': Components.EonForm;
    'EonInput': Components.EonInput;
    'EonUpload': Components.EonUpload;
    'EonEngageBootstrap': Components.EonEngageBootstrap;
    'EonEngageHome': Components.EonEngageHome;
    'EonEngageRoot': Components.EonEngageRoot;
  }

  interface StencilIntrinsicElements {
    'eon-button': Components.EonButtonAttributes;
    'eon-flip': Components.EonFlipAttributes;
    'eon-form': Components.EonFormAttributes;
    'eon-input': Components.EonInputAttributes;
    'eon-upload': Components.EonUploadAttributes;
    'eon-engage-bootstrap': Components.EonEngageBootstrapAttributes;
    'eon-engage-home': Components.EonEngageHomeAttributes;
    'eon-engage-root': Components.EonEngageRootAttributes;
  }


  interface HTMLEonButtonElement extends Components.EonButton, HTMLStencilElement {}
  var HTMLEonButtonElement: {
    prototype: HTMLEonButtonElement;
    new (): HTMLEonButtonElement;
  };

  interface HTMLEonFlipElement extends Components.EonFlip, HTMLStencilElement {}
  var HTMLEonFlipElement: {
    prototype: HTMLEonFlipElement;
    new (): HTMLEonFlipElement;
  };

  interface HTMLEonFormElement extends Components.EonForm, HTMLStencilElement {}
  var HTMLEonFormElement: {
    prototype: HTMLEonFormElement;
    new (): HTMLEonFormElement;
  };

  interface HTMLEonInputElement extends Components.EonInput, HTMLStencilElement {}
  var HTMLEonInputElement: {
    prototype: HTMLEonInputElement;
    new (): HTMLEonInputElement;
  };

  interface HTMLEonUploadElement extends Components.EonUpload, HTMLStencilElement {}
  var HTMLEonUploadElement: {
    prototype: HTMLEonUploadElement;
    new (): HTMLEonUploadElement;
  };

  interface HTMLEonEngageBootstrapElement extends Components.EonEngageBootstrap, HTMLStencilElement {}
  var HTMLEonEngageBootstrapElement: {
    prototype: HTMLEonEngageBootstrapElement;
    new (): HTMLEonEngageBootstrapElement;
  };

  interface HTMLEonEngageHomeElement extends Components.EonEngageHome, HTMLStencilElement {}
  var HTMLEonEngageHomeElement: {
    prototype: HTMLEonEngageHomeElement;
    new (): HTMLEonEngageHomeElement;
  };

  interface HTMLEonEngageRootElement extends Components.EonEngageRoot, HTMLStencilElement {}
  var HTMLEonEngageRootElement: {
    prototype: HTMLEonEngageRootElement;
    new (): HTMLEonEngageRootElement;
  };

  interface HTMLElementTagNameMap {
    'eon-button': HTMLEonButtonElement
    'eon-flip': HTMLEonFlipElement
    'eon-form': HTMLEonFormElement
    'eon-input': HTMLEonInputElement
    'eon-upload': HTMLEonUploadElement
    'eon-engage-bootstrap': HTMLEonEngageBootstrapElement
    'eon-engage-home': HTMLEonEngageHomeElement
    'eon-engage-root': HTMLEonEngageRootElement
  }

  interface ElementTagNameMap {
    'eon-button': HTMLEonButtonElement;
    'eon-flip': HTMLEonFlipElement;
    'eon-form': HTMLEonFormElement;
    'eon-input': HTMLEonInputElement;
    'eon-upload': HTMLEonUploadElement;
    'eon-engage-bootstrap': HTMLEonEngageBootstrapElement;
    'eon-engage-home': HTMLEonEngageHomeElement;
    'eon-engage-root': HTMLEonEngageRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
